/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-12-21 at 15:04:03 UTC 
 * Modify at your own risk.
 */

package ch.hesso.master.sweetcity.webservice.account;

import ch.hesso.master.sweetcity.model.Account;
import ch.hesso.master.sweetcity.model.AccountCollection;

/**
 * Service definition for AccountService (v1).
 *
 * <p>
 * API to manage user on SweetCity.
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AccountServiceRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class AccountService extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.19.0 of the accountService library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://mse-sweetcity.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "accountService/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public AccountService(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  AccountService(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * An accessor for creating requests from the AccountServiceOperations collection.
   *
   * <p>The typical use is:</p>
   * <pre>
   *   {@code AccountService accountService = new AccountService(...);}
   *   {@code AccountService.AccountServiceOperations.List request = accountService.accountService().list(parameters ...)}
   * </pre>
   *
   * @return the resource collection
   */
  public AccountServiceOperations accountService() {
    return new AccountServiceOperations();
  }

  /**
   * The "accountService" collection of methods.
   */
  public class AccountServiceOperations {

    /**
     * Create a request for the method "accountService.getCurrentAccount".
     *
     * This request holds the parameters needed by the accountService server.  After setting any
     * optional parameters, call the {@link GetCurrentAccount#execute()} method to invoke the remote
     * operation.
     *
     * @return the request
     */
    public GetCurrentAccount getCurrentAccount() throws java.io.IOException {
      GetCurrentAccount result = new GetCurrentAccount();
      initialize(result);
      return result;
    }

    public class GetCurrentAccount extends AccountServiceRequest<Account> {

      private static final String REST_PATH = "get";

      /**
       * Create a request for the method "accountService.getCurrentAccount".
       *
       * This request holds the parameters needed by the the accountService server.  After setting any
       * optional parameters, call the {@link GetCurrentAccount#execute()} method to invoke the remote
       * operation. <p> {@link GetCurrentAccount#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after
       * invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected GetCurrentAccount() {
        super(AccountService.this, "GET", REST_PATH, null, Account.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public GetCurrentAccount setAlt(java.lang.String alt) {
        return (GetCurrentAccount) super.setAlt(alt);
      }

      @Override
      public GetCurrentAccount setFields(java.lang.String fields) {
        return (GetCurrentAccount) super.setFields(fields);
      }

      @Override
      public GetCurrentAccount setKey(java.lang.String key) {
        return (GetCurrentAccount) super.setKey(key);
      }

      @Override
      public GetCurrentAccount setOauthToken(java.lang.String oauthToken) {
        return (GetCurrentAccount) super.setOauthToken(oauthToken);
      }

      @Override
      public GetCurrentAccount setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (GetCurrentAccount) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public GetCurrentAccount setQuotaUser(java.lang.String quotaUser) {
        return (GetCurrentAccount) super.setQuotaUser(quotaUser);
      }

      @Override
      public GetCurrentAccount setUserIp(java.lang.String userIp) {
        return (GetCurrentAccount) super.setUserIp(userIp);
      }

      @Override
      public GetCurrentAccount set(String parameterName, Object value) {
        return (GetCurrentAccount) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "accountService.ranking".
     *
     * This request holds the parameters needed by the accountService server.  After setting any
     * optional parameters, call the {@link Ranking#execute()} method to invoke the remote operation.
     *
     * @return the request
     */
    public Ranking ranking() throws java.io.IOException {
      Ranking result = new Ranking();
      initialize(result);
      return result;
    }

    public class Ranking extends AccountServiceRequest<AccountCollection> {

      private static final String REST_PATH = "ranking";

      /**
       * Create a request for the method "accountService.ranking".
       *
       * This request holds the parameters needed by the the accountService server.  After setting any
       * optional parameters, call the {@link Ranking#execute()} method to invoke the remote operation.
       * <p> {@link
       * Ranking#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)} must
       * be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @since 1.13
       */
      protected Ranking() {
        super(AccountService.this, "GET", REST_PATH, null, AccountCollection.class);
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Ranking setAlt(java.lang.String alt) {
        return (Ranking) super.setAlt(alt);
      }

      @Override
      public Ranking setFields(java.lang.String fields) {
        return (Ranking) super.setFields(fields);
      }

      @Override
      public Ranking setKey(java.lang.String key) {
        return (Ranking) super.setKey(key);
      }

      @Override
      public Ranking setOauthToken(java.lang.String oauthToken) {
        return (Ranking) super.setOauthToken(oauthToken);
      }

      @Override
      public Ranking setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Ranking) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Ranking setQuotaUser(java.lang.String quotaUser) {
        return (Ranking) super.setQuotaUser(quotaUser);
      }

      @Override
      public Ranking setUserIp(java.lang.String userIp) {
        return (Ranking) super.setUserIp(userIp);
      }

      @Override
      public Ranking set(String parameterName, Object value) {
        return (Ranking) super.set(parameterName, value);
      }
    }
    /**
     * Create a request for the method "accountService.register".
     *
     * This request holds the parameters needed by the accountService server.  After setting any
     * optional parameters, call the {@link Register#execute()} method to invoke the remote operation.
     *
     * @param login
     * @return the request
     */
    public Register register(java.lang.String login) throws java.io.IOException {
      Register result = new Register(login);
      initialize(result);
      return result;
    }

    public class Register extends AccountServiceRequest<Void> {

      private static final String REST_PATH = "register/{login}";

      /**
       * Create a request for the method "accountService.register".
       *
       * This request holds the parameters needed by the the accountService server.  After setting any
       * optional parameters, call the {@link Register#execute()} method to invoke the remote operation.
       * <p> {@link
       * Register#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
       * must be called to initialize this instance immediately after invoking the constructor. </p>
       *
       * @param login
       * @since 1.13
       */
      protected Register(java.lang.String login) {
        super(AccountService.this, "GET", REST_PATH, null, Void.class);
        this.login = com.google.api.client.util.Preconditions.checkNotNull(login, "Required parameter login must be specified.");
      }

      @Override
      public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
        return super.executeUsingHead();
      }

      @Override
      public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
        return super.buildHttpRequestUsingHead();
      }

      @Override
      public Register setAlt(java.lang.String alt) {
        return (Register) super.setAlt(alt);
      }

      @Override
      public Register setFields(java.lang.String fields) {
        return (Register) super.setFields(fields);
      }

      @Override
      public Register setKey(java.lang.String key) {
        return (Register) super.setKey(key);
      }

      @Override
      public Register setOauthToken(java.lang.String oauthToken) {
        return (Register) super.setOauthToken(oauthToken);
      }

      @Override
      public Register setPrettyPrint(java.lang.Boolean prettyPrint) {
        return (Register) super.setPrettyPrint(prettyPrint);
      }

      @Override
      public Register setQuotaUser(java.lang.String quotaUser) {
        return (Register) super.setQuotaUser(quotaUser);
      }

      @Override
      public Register setUserIp(java.lang.String userIp) {
        return (Register) super.setUserIp(userIp);
      }

      @com.google.api.client.util.Key
      private java.lang.String login;

      /**

       */
      public java.lang.String getLogin() {
        return login;
      }

      public Register setLogin(java.lang.String login) {
        this.login = login;
        return this;
      }

      @Override
      public Register set(String parameterName, Object value) {
        return (Register) super.set(parameterName, value);
      }
    }

  }

  /**
   * Builder for {@link AccountService}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link AccountService}. */
    @Override
    public AccountService build() {
      return new AccountService(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AccountServiceRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAccountServiceRequestInitializer(
        AccountServiceRequestInitializer accountserviceRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(accountserviceRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
